# -*- coding: utf-8 -*-
r"""
Reconstructs a `run_level_features_all.csv`-compatible feature table from
raw PHM2010 signals, for conditions C1/C4/C6 only (all this project's D1
task needs).

Why this script exists: the original feature-extraction script that
produced `代码/main_experiment_3_fgds_psi_optimized.py`'s expected input
(`run_level_features_all.csv`) was not found anywhere in this project or on
this machine (see baselines/htt_net/README.md, "Data availability"). The
raw PHM2010 dataset was subsequently made available at
`archive/c{1,4,6}/c{1,4,6}/c_{cond}_{run:03d}.csv` (7-channel signal, no
header, standard Kaggle "tobbyrui/phm2010" layout) plus
`archive/c{1,4,6}/c{1,4,6}_wear.csv` (columns: cut, flute_1, flute_2,
flute_3 -- matches the exact forbidden-column-name list already present in
`main_experiment_3_fgds_psi_optimized.py`'s `is_meta_or_label_col()`,
confirming this is the right raw source).

This script computes a standard pool of per-cut time-domain statistical
features per channel (mean/std/rms/max/min/peak-to-peak/skew/kurtosis/
crest-factor -- common practice for tool-wear feature engineering, matching
the kind of "traditional machine learning" feature basis the DC-PSR
manuscript itself discusses in its related work) and writes a CSV with the
same column contract the existing pipeline expects:
    - "condition" in {C1, C4, C6}
    - "run_id" (the cut/pass index, 1..315)
    - "VB" (= mean of flute_1, flute_2, flute_3, matching the paper's own
      "mean of the three flank-wear values was selected as the tool-wear
      value", §3.1.1)
    - a pool of additional numeric feature columns (raw sensor features);
      `代码/main_experiment_3_fgds_psi_optimized.py`'s own
      `get_raw_numeric_sensor_cols()` / `is_meta_or_label_col()` /
      `select_features_train_only()` handle picking, causally transforming
      (rel/slope/online-rank), and down-selecting these exactly as they
      already do for B1-B12 -- nothing about that downstream logic changes.

IMPORTANT: this is NOT a reproduction of whatever exact feature set the
manuscript's own (now-missing) run_level_features_all.csv contained -- that
file's construction is unknown. Any B1-B12 numbers regenerated by
`代码/7.4对比实验.py` against *this* reconstructed file are only comparable
to HTT-Net's numbers computed on the same file, not necessarily to whatever
numbers currently appear in the manuscript draft (which were computed on
the original, now-unavailable file). This must be stated wherever these
numbers are reported.

Usage:
    python build_run_level_features.py
"""
from __future__ import annotations

import time
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import kurtosis, skew

ARCHIVE_ROOT = Path(__file__).resolve().parents[3] / "archive"
OUT_PATH = Path(__file__).resolve().parent / "run_level_features_all.csv"

CONDITIONS = ["c1", "c4", "c6"]
COND_NAME_MAP = {"c1": "C1", "c4": "C4", "c6": "C6"}
CHANNEL_NAMES = ["Fx", "Fy", "Fz", "Vx", "Vy", "Vz", "AE"]  # standard PHM2010 7-channel order
N_RUNS = 315


def channel_features(x: np.ndarray, prefix: str) -> dict:
    x = x.astype(np.float64)
    rms = float(np.sqrt(np.mean(x ** 2)))
    mx, mn = float(x.max()), float(x.min())
    crest = float(np.max(np.abs(x)) / (rms + 1e-12))
    return {
        f"{prefix}_mean": float(x.mean()),
        f"{prefix}_std": float(x.std()),
        f"{prefix}_rms": rms,
        f"{prefix}_max": mx,
        f"{prefix}_min": mn,
        f"{prefix}_ptp": mx - mn,
        f"{prefix}_skew": float(skew(x)),
        f"{prefix}_kurt": float(kurtosis(x)),
        f"{prefix}_crest": crest,
    }


def build_condition(cond: str) -> pd.DataFrame:
    cond_dir = ARCHIVE_ROOT / cond / cond
    wear_path = ARCHIVE_ROOT / cond / f"{cond}_wear.csv"
    wear = pd.read_csv(wear_path)
    wear["VB"] = wear[["flute_1", "flute_2", "flute_3"]].mean(axis=1)
    vb_by_cut = dict(zip(wear["cut"].astype(int), wear["VB"].astype(float)))

    rows = []
    t0 = time.time()
    for run_id in range(1, N_RUNS + 1):
        fpath = cond_dir / f"c_{cond[1]}_{run_id:03d}.csv"
        if not fpath.exists():
            continue
        sig = pd.read_csv(fpath, header=None, dtype="float32", engine="c").values
        if sig.shape[1] != 7:
            raise ValueError(f"{fpath} has {sig.shape[1]} columns, expected 7")
        row = {"condition": COND_NAME_MAP[cond], "run_id": run_id, "VB": vb_by_cut.get(run_id, np.nan)}
        for ch_idx, ch_name in enumerate(CHANNEL_NAMES):
            row.update(channel_features(sig[:, ch_idx], ch_name))
        rows.append(row)
        if run_id % 50 == 0:
            print(f"  {cond}: {run_id}/{N_RUNS} cuts processed ({time.time()-t0:.1f}s elapsed)")
    print(f"{cond}: done, {len(rows)} runs, {time.time()-t0:.1f}s")
    return pd.DataFrame(rows)


def main():
    if not ARCHIVE_ROOT.exists():
        raise FileNotFoundError(f"Raw PHM2010 archive not found at {ARCHIVE_ROOT}")
    parts = []
    for cond in CONDITIONS:
        parts.append(build_condition(cond))
    out = pd.concat(parts, axis=0).sort_values(["condition", "run_id"]).reset_index(drop=True)
    out.to_csv(OUT_PATH, index=False)
    print(f"\nWrote {len(out)} rows, {out.shape[1]} columns to {OUT_PATH}")
    print(out.groupby("condition").size())


if __name__ == "__main__":
    main()
